start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: container
      type: String
      dist:
        type: constant_string
        value: kube-state-metrics
    - name: created_by_kind
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: created_by_kind0
              weight: 1
    - name: created_by_name
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: created_by_name0
              weight: 1
    - name: endpoint
      type: String
      dist:
        type: constant_string
        value: http
    - name: env
      type: String
      dist:
        type: constant_string
        value: qa
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: host_ip
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: host_ip0
              weight: 1
    - name: host_network
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: host_network0
              weight: 1
    - name: instance
      type: String
      dist:
        type: replica_string
        replica: 5
        replica_prefix: instance-
    - name: job
      type: String
      dist:
        type: constant_string
        value: kube-state-metrics
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 50
        replica_prefix: app-
    - name: node
      type: String
      dist:
        type: replica_string
        replica: 5
        replica_prefix: node-
    - name: pod
      type: String
      dist:
        type: replica_string
        replica: 2
        replica_prefix: pod-
    - name: pod_ip
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: pod_ip0
              weight: 1
    - name: priority_class
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: priority_class0
              weight: 1
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
    - name: service
      type: String
      dist:
        type: constant_string
        value: prometheus-kube-state-metrics
    - name: uid
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: uid0
              weight: 1
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
