start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: endpoint
      type: String
      dist:
        type: constant_string
        value: http-metrics
    - name: env
      type: String
      dist:
        type: constant_string
        value: qa
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: instance
      type: String
      dist:
        type: replica_string
        replica: 1
        replica_prefix: instance-
    - name: job
      type: String
      dist:
        type: constant_string
        value: kube-proxy
    - name: le
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: "47"
              weight: 1
            - value: "75"
              weight: 1
            - value: "58"
              weight: 1
            - value: "27"
              weight: 1
            - value: "100"
              weight: 1
            - value: "95"
              weight: 1
            - value: "37"
              weight: 1
            - value: "1"
              weight: 1
            - value: "59"
              weight: 1
            - value: "38"
              weight: 1
            - value: "43"
              weight: 1
            - value: "41"
              weight: 1
            - value: "10"
              weight: 1
            - value: "20"
              weight: 1
            - value: "23"
              weight: 1
            - value: "29"
              weight: 1
            - value: +Inf
              weight: 1
            - value: "16"
              weight: 1
            - value: "30"
              weight: 1
            - value: "39"
              weight: 1
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 18
        replica_prefix: app-
    - name: pod
      type: String
      dist:
        type: replica_string
        replica: 2
        replica_prefix: pod-
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
    - name: service
      type: String
      dist:
        type: constant_string
        value: prometheus-kube-prometheus-kube-proxy
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
