start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: endpoint
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: endpoint0
              weight: 1
    - name: env
      type: String
      dist:
        type: constant_string
        value: qa
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: instance
      type: String
      dist:
        type: replica_string
        replica: 1
        replica_prefix: instance-
    - name: job
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: kubelet
              weight: 1
            - value: apiserver
              weight: 1
            - value: kubernetes-pods
              weight: 1
    - name: kubernetes_namespace
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: kubernetes_namespace0
              weight: 1
    - name: kubernetes_pod_name
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: kubernetes_pod_name0
              weight: 1
    - name: le
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: "9.999999999999999e-05"
              weight: 1
            - value: "10"
              weight: 1
            - value: +Inf
              weight: 1
            - value: "0.001"
              weight: 1
            - value: "0.01"
              weight: 1
            - value: "0.1"
              weight: 1
    - name: metrics_path
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: /metrics
              weight: 1
    - name: name
      type: String
      dist:
        type: constant_string
        value: name0
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 18
        replica_prefix: app-
    - name: node
      type: String
      dist:
        type: replica_string
        replica: 1
        replica_prefix: node-
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
    - name: service
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: service0
              weight: 1
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
