start: "2021-01-01T00:00:00Z"
end: "2021-01-01T00:00:00Z"
interval: 30
tags:
    - name: cluster
      type: String
      dist:
        type: constant_string
        value: eks-us-east-1-qa1
    - name: container
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: container0
              weight: 1
            - value: container1
              weight: 1
    - name: device
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: /dev/nvme2n1
              weight: 1
            - value: /dev/nvme0n1
              weight: 1
            - value: /dev/nvme1n1
              weight: 1
            - value: /dev/nvme6n1
              weight: 1
            - value: /dev/nvme4n1
              weight: 1
            - value: /dev/nvme5n1
              weight: 1
            - value: /dev/nvme3n1
              weight: 1
            - value: /dev/nvme7n1
              weight: 1
    - name: endpoint
      type: String
      dist:
        type: constant_string
        value: https-metrics
    - name: env
      type: String
      dist:
        type: constant_string
        value: qa
    - name: holiday
      type: String
      dist:
        type: constant_string
        value: "false"
    - name: id
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: id0
              weight: 1
            - value: id1
              weight: 1
    - name: image
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: image0
              weight: 1
            - value: image1
              weight: 1
    - name: instance
      type: String
      dist:
        type: replica_string
        replica: 2
        replica_prefix: instance-
    - name: job
      type: String
      dist:
        type: constant_string
        value: kubelet
    - name: metrics_path
      type: String
      dist:
        type: constant_string
        value: /metrics/cadvisor
    - name: name
      type: String
      dist:
        type: weighted_preset
        preset:
            - value: name0
              weight: 1
            - value: name1
              weight: 1
    - name: namespace
      type: String
      dist:
        type: replica_string
        replica: 40
        replica_prefix: app-
    - name: node
      type: String
      dist:
        type: replica_string
        replica: 4
        replica_prefix: node-
    - name: pod
      type: String
      dist:
        type: replica_string
        replica: 2
        replica_prefix: pod-
    - name: prometheus
      type: String
      dist:
        type: constant_string
        value: monitoring/prometheus-kube-prometheus-prometheus
    - name: prometheus_replica
      type: String
      dist:
        type: constant_string
        value: prometheus-prometheus-kube-prometheus-prometheus-0
    - name: service
      type: String
      dist:
        type: constant_string
        value: prometheus-kube-prometheus-kubelet
fields:
    - name: greptime_value
      type: Float
      dist:
        type: mono_inc
        lower_bound: 1
        upper_bound: 1000
        step: 10
