end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    preset:
    - value: read
      weight: 1
    - value: all
      weight: 1
    - value: write
      weight: 1
    type: weighted_preset
  name: verb
  type: String
