end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    preset:
    - value: null
      weight: 1
    - value: vmstorage
      weight: 1
    - value: vminsert
      weight: 1
    - value: vmselect
      weight: 1
    type: weighted_preset
  name: app
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: controller
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_component
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: internal
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_instance
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: Helm
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_managed_by
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: ingress-nginx
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_name
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: ingress-nginx
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_part_of
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: 1.9.4
      weight: 1
    type: weighted_preset
  name: app_kubernetes_io_version
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster-eks-us-east-1-qa1
      weight: 1
    - value: internal-ingress-nginx-eks-us-east-1-qa1
      weight: 1
    type: weighted_preset
  name: argocd_argoproj_io_instance
  type: String
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: etcd
      weight: 1
    - value: null
      weight: 1
    - value: coredns
      weight: 1
    - value: prometheus
      weight: 1
    - value: node-exporter
      weight: 1
    - value: controller
      weight: 1
    - value: external-dns
      weight: 1
    - value: tempo
      weight: 1
    - value: config-reloader
      weight: 1
    - value: kube-prometheus-stack
      weight: 1
    - value: alertmanager
      weight: 1
    - value: reloader-reloader
      weight: 1
    - value: metrics
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    preset:
    - value: client
      weight: 1
    - value: http-metrics
      weight: 1
    - value: null
      weight: 1
    - value: http-web
      weight: 1
    - value: https-metrics
      weight: 1
    - value: metrics
      weight: 1
    - value: http
      weight: 1
    - value: tempo-prom-metrics
      weight: 1
    - value: reloader-web
      weight: 1
    - value: https
      weight: 1
    type: weighted_preset
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster-0.11.4
      weight: 1
    - value: ingress-nginx-4.8.3
      weight: 1
    type: weighted_preset
  name: helm_sh_chart
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    type: weighted_preset
  name: hostname
  type: String
- dist:
    preset:
    - value: 10.0.169.75:2379
      weight: 1
    - value: 10.0.169.179:10249
      weight: 1
    - value: 10.0.166.220:2379
      weight: 1
    - value: 10.0.174.148:8482
      weight: 1
    - value: 10.0.164.0:9153
      weight: 1
    - value: 10.0.166.41:9090
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.166.131:10249
      weight: 1
    - value: 10.0.162.77:10249
      weight: 1
    - value: 10.0.174.40:10254
      weight: 1
    - value: 10.0.162.53:9100
      weight: 1
    - value: 10.0.166.131:9100
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.172.86:10254
      weight: 1
    - value: 10.0.162.77:9100
      weight: 1
    - value: 10.0.162.59:8482
      weight: 1
    - value: 10.0.165.32:23227
      weight: 1
    - value: 10.0.167.225:9153
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.172.113:7979
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: t4g.large
      weight: 1
    type: weighted_preset
  name: instance_type
  type: String
- dist:
    preset:
    - value: etcd/etcd
      weight: 1
    - value: kube-proxy
      weight: 1
    - value: kubernetes-endpoints
      weight: 1
    - value: coredns
      weight: 1
    - value: prometheus-kube-prometheus-prometheus
      weight: 1
    - value: kubelet
      weight: 1
    - value: node-exporter
      weight: 1
    - value: ingress-nginx-controller-metrics
      weight: 1
    - value: kubernetes-pods
      weight: 1
    - value: external-dns
      weight: 1
    - value: dedicated-etcd/etcd
      weight: 1
    - value: tempo
      weight: 1
    - value: prometheus-kube-prometheus-alertmanager
      weight: 1
    - value: apiserver
      weight: 1
    - value: prometheus-kube-prometheus-operator
      weight: 1
    - value: reloader/reloader-reloader
      weight: 1
    - value: argo-workflows-controller
      weight: 1
    - value: karpenter
      weight: 1
    - value: gcp-redis-metrics
      weight: 1
    type: weighted_preset
  name: job
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster-vmstorage
      weight: 1
    - value: internal-ingress-nginx-controller
      weight: 1
    - value: victoria-metrics-cluster-vminsert
      weight: 1
    - value: victoria-metrics-cluster-vmselect
      weight: 1
    type: weighted_preset
  name: kubernetes_name
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: jarvis
      weight: 1
    - value: gcrm
      weight: 1
    type: weighted_preset
  name: kubernetes_namespace
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: jarvis-producer-59875c87-sqjbv
      weight: 1
    - value: jarvis-api-6d9988949f-vqdvl
      weight: 1
    - value: jarvis-consumer-86999fbb4f-f6gdm
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    type: weighted_preset
  name: kubernetes_pod_name
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: /metrics
      weight: 1
    type: weighted_preset
  name: metrics_path
  type: String
- dist:
    preset:
    - value: etcd
      weight: 1
    - value: kube-system
      weight: 1
    - value: null
      weight: 1
    - value: monitoring
      weight: 1
    - value: ingress-nginx
      weight: 1
    - value: external-dns
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: tempo
      weight: 1
    - value: default
      weight: 1
    - value: reloader
      weight: 1
    - value: argo-workflows
      weight: 1
    - value: karpenter
      weight: 1
    - value: gcp
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: etcd-0
      weight: 1
    - value: kube-proxy-htsdp
      weight: 1
    - value: etcd-1
      weight: 1
    - value: null
      weight: 1
    - value: coredns-586b798467-mj7f7
      weight: 1
    - value: prometheus-prometheus-kube-prometheus-prometheus-0
      weight: 1
    - value: kube-proxy-9r8vq
      weight: 1
    - value: kube-proxy-vccv8
      weight: 1
    - value: prometheus-prometheus-node-exporter-8fcnl
      weight: 1
    - value: prometheus-prometheus-node-exporter-xwxj4
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-7qvh7
      weight: 1
    - value: prometheus-prometheus-node-exporter-f9zfx
      weight: 1
    - value: coredns-586b798467-sbb7w
      weight: 1
    - value: external-dns-5c99648766-lcjg4
      weight: 1
    - value: tempo-0
      weight: 1
    - value: alertmanager-prometheus-kube-prometheus-alertmanager-0
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-frtzs
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: prometheus-kube-prometheus-operator-7dc7f7857d-9gcjt
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: us-east-1
      weight: 1
    type: weighted_preset
  name: region
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: prometheus-kube-prometheus-kube-proxy
      weight: 1
    - value: prometheus-kube-prometheus-coredns
      weight: 1
    - value: prometheus-kube-prometheus-prometheus
      weight: 1
    - value: prometheus-kube-prometheus-kubelet
      weight: 1
    - value: prometheus-prometheus-node-exporter
      weight: 1
    - value: ingress-nginx-controller-metrics
      weight: 1
    - value: external-dns
      weight: 1
    - value: tempo
      weight: 1
    - value: prometheus-kube-prometheus-alertmanager
      weight: 1
    - value: kubernetes
      weight: 1
    - value: prometheus-kube-prometheus-operator
      weight: 1
    - value: argo-workflows-controller
      weight: 1
    - value: karpenter
      weight: 1
    - value: gcp-redis-metrics
      weight: 1
    type: weighted_preset
  name: service
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: us-east-1a
      weight: 1
    type: weighted_preset
  name: zone
  type: String
