end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: http-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: 10.0.175.164:10249
      weight: 1
    - value: 10.0.162.77:10249
      weight: 1
    - value: 10.0.169.179:10249
      weight: 1
    - value: 10.0.162.53:10249
      weight: 1
    - value: 10.0.166.131:10249
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-proxy
  name: job
  type: String
- dist:
    preset:
    - value: '47'
      weight: 1
    - value: '75'
      weight: 1
    - value: '58'
      weight: 1
    - value: '27'
      weight: 1
    - value: '100'
      weight: 1
    - value: '95'
      weight: 1
    - value: '37'
      weight: 1
    - value: '1'
      weight: 1
    - value: '59'
      weight: 1
    - value: '38'
      weight: 1
    - value: '43'
      weight: 1
    - value: '41'
      weight: 1
    - value: '10'
      weight: 1
    - value: '20'
      weight: 1
    - value: '23'
      weight: 1
    - value: '29'
      weight: 1
    - value: +Inf
      weight: 1
    - value: '16'
      weight: 1
    - value: '30'
      weight: 1
    - value: '39'
      weight: 1
    type: weighted_preset
  name: le
  type: String
- dist:
    type: constant_string
    value: kube-system
  name: namespace
  type: String
- dist:
    preset:
    - value: kube-proxy-5q9j4
      weight: 1
    - value: kube-proxy-vccv8
      weight: 1
    - value: kube-proxy-htsdp
      weight: 1
    - value: kube-proxy-vrnnh
      weight: 1
    - value: kube-proxy-9r8vq
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kube-proxy
  name: service
  type: String
