end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: Ready
      weight: 1
    - value: PIDPressure
      weight: 1
    - value: MemoryPressure
      weight: 1
    - value: DiskPressure
      weight: 1
    type: weighted_preset
  name: condition
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: container
  type: String
- dist:
    type: constant_string
    value: http
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    type: constant_string
    value: 10.0.169.98:8080
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: job
  type: String
- dist:
    type: constant_string
    value: monitoring
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics-8f664f9c8-cdcrg
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics
  name: service
  type: String
- dist:
    preset:
    - value: 'false'
      weight: 1
    - value: 'true'
      weight: 1
    - value: unknown
      weight: 1
    type: weighted_preset
  name: status
  type: String
