end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: greptimedb
      weight: 1
    - value: greptimedb-operator
      weight: 1
    - value: gcrm
      weight: 1
    - value: kube-system
      weight: 1
    - value: monitoring
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: vector
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: tudigong
      weight: 1
    - value: external-dns
      weight: 1
    - value: argo-cd
      weight: 1
    - value: robusta
      weight: 1
    - value: gcp
      weight: 1
    - value: etcd
      weight: 1
    - value: argo-workflows
      weight: 1
    - value: debug
      weight: 1
    - value: tempo
      weight: 1
    - value: jarvis
      weight: 1
    - value: kafka
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: greptimedb-meta-6ccc6598cd-7qg59
      weight: 1
    - value: greptimedb-operator-7fb65497bc-m5dgw
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    - value: kube-proxy-5q9j4
      weight: 1
    - value: efs-csi-node-pnq5t
      weight: 1
    - value: prometheus-prometheus-kube-prometheus-prometheus-0
      weight: 1
    - value: efs-csi-node-l4rxj
      weight: 1
    - value: aws-node-cjttw
      weight: 1
    - value: etcd-2
      weight: 1
    - value: internal-ingress-nginx-controller-76d547b95b-vr4rj
      weight: 1
    - value: vector-qwpl5
      weight: 1
    - value: ebs-csi-node-qkksr
      weight: 1
    - value: internal-ingress-nginx-controller-76d547b95b-lvzhp
      weight: 1
    - value: efs-csi-node-t2vwk
      weight: 1
    - value: prometheus-kube-prometheus-operator-7dc7f7857d-9gcjt
      weight: 1
    - value: vector-2xvqg
      weight: 1
    - value: ebs-csi-node-297wb
      weight: 1
    - value: internal-greptimedb-standalone-0
      weight: 1
    - value: tudigong-6d886f5b4f-hrkt8
      weight: 1
    - value: external-dns-5c99648766-lcjg4
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    preset:
    - value: greptimedb-meta
      weight: 1
    - value: greptimedb-operator
      weight: 1
    - value: gcrm
      weight: 1
    - value: kube-proxy
      weight: 1
    - value: efs-csi-node
      weight: 1
    - value: prometheus-prometheus-kube-prometheus-prometheus
      weight: 1
    - value: aws-node
      weight: 1
    - value: etcd
      weight: 1
    - value: internal-ingress-nginx-controller
      weight: 1
    - value: vector
      weight: 1
    - value: ebs-csi-node
      weight: 1
    - value: prometheus-kube-prometheus-operator
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: tudigong
      weight: 1
    - value: external-dns
      weight: 1
    - value: dashboard
      weight: 1
    - value: greptimedb-datanode
      weight: 1
    - value: argo-cd-argocd-repo-server
      weight: 1
    - value: argo-cd-argocd-applicationset-controller
      weight: 1
    - value: ebs-csi-controller
      weight: 1
    type: weighted_preset
  name: workload
  type: String
- dist:
    preset:
    - value: deployment
      weight: 1
    - value: daemonset
      weight: 1
    - value: statefulset
      weight: 1
    type: weighted_preset
  name: workload_type
  type: String
