end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: '500'
      weight: 1
    - value: '200'
      weight: 1
    type: weighted_preset
  name: code
  type: String
- dist:
    preset:
    - value: https
      weight: 1
    - value: https-metrics
      weight: 1
    - value: http-metrics
      weight: 1
    - value: null
      weight: 1
    type: weighted_preset
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: '[::1]:443'
      weight: 1
    type: weighted_preset
  name: host
  type: String
- dist:
    preset:
    - value: 10.0.180.195:443
      weight: 1
    - value: 10.0.161.185:443
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.166.131:10249
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.163.161:8080
      weight: 1
    - value: 10.0.162.77:10249
      weight: 1
    - value: 10.0.162.53:10249
      weight: 1
    - value: 10.0.169.179:10249
      weight: 1
    - value: 10.0.175.164:10249
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    preset:
    - value: kubelet
      weight: 1
    type: weighted_preset
  name: job
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: gcrm
      weight: 1
    type: weighted_preset
  name: kubernetes_namespace
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    type: weighted_preset
  name: kubernetes_pod_name
  type: String
- dist:
    preset:
    - value: GET
      weight: 1
    - value: POST
      weight: 1
    - value: PUT
      weight: 1
    - value: PATCH
      weight: 1
    - value: DELETE
      weight: 1
    type: weighted_preset
  name: method
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: /metrics
      weight: 1
    type: weighted_preset
  name: metrics_path
  type: String
- dist:
    preset:
    - value: default
      weight: 1
    - value: kube-system
      weight: 1
    - value: null
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: pod-1
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    preset:
    - value: service-1
      weight: 1
    type: weighted_preset
  name: service
  type: String
