end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: https
      weight: 1
    type: weighted_preset
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: 10.0.180.195:443
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    preset:
    - value: apiserver
      weight: 1
    - value: kubelet
      weight: 1
    - value: kubernetes-pods
      weight: 1
    type: weighted_preset
  name: job
  type: String
- dist:
    preset:
    - value: namespace-1
      weight: 1
    type: weighted_preset
  name: kubernetes_namespace
  type: String
- dist:
    preset:
    - value: pod-1
      weight: 1
    type: weighted_preset
  name: kubernetes_pod_name
  type: String
- dist:
    preset:
    - value: /metrics
      weight: 1
    type: weighted_preset
  name: metrics_path
  type: String
- dist:
    preset:
    - value: open_api_v3_aggregation_controller
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: default
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    preset:
    - value: kubernetes
      weight: 1
    - value: prometheus-kube-prometheus-kubelet
      weight: 1
    type: weighted_preset
  name: service
  type: String
