start: "2024-02-08T00:00:00+08:00"
end: "2024-03-08T00:00:00+08:00"
interval: 30 # 30s
precision: 1000 # ms
tags:
  - name: endpoint
    type: String
    dist:
      type: constant_string
      value: 'https-metrics'
  - name: env
    type: STRING
    dist:
      type: constant_string
      value: 'prod'
  - name: holiday
    type: String
    dist:
      type: constant_string
      value: 'false'
  - name: instance
    type: String
    dist:
      type: replica_string
      replica_prefix: '10.0.162.'
      replica: 30
  - name: job_name
    type: String
    dist:
      type: constant_string
      value: 'kubelet'
  - name: metrics_path
    type: String
    dist:
      type: constant_string
      value: '/metrics'
  - name: namespace
    type: String
    dist:
      type: constant_string
      value: 'kube-system'
  - name: le
    type: String
    dist:
      type: weighted_preset
      preset:
        - value: '+Inf'
          weight: 1
        - value: '0.005'
          weight: 1
        - value: '0.0125'
          weight: 1
        - value: '0.03125'
          weight: 1
        - value: '0.078125'
          weight: 1
        - value: '0.1953125'
          weight: 1
        - value: '0.48828125'
          weight: 1
        - value: '1.220703125'
          weight: 1
        - value: '119.20928955078125'
          weight: 1
        - value: '19.073486328125'
          weight: 1
        - value: '298.0232238769531'
          weight: 1
        - value: '3.0517578125'
          weight: 1
        - value: '47.6837158203125'
          weight: 1
        - value: '7.62939453125'
          weight: 1
        - value: '745.0580596923828'
          weight: 1

fields:
  - name: greptime_value
    type: Float
    dist: 
      type: constant_float
      value: 0.0
