start: "2024-02-08T00:00:00+08:00"
end: "2024-03-08T00:00:00+08:00"
interval: 30 # 30s
precision: 1000 # ms
tags:
  - name: endpoint
    type: String
    dist:
      type: constant_string
      value: 'https-metrics'
  - name: env
    type: STRING
    dist:
      type: constant_string
      value: 'prod'
  - name: holiday
    type: String
    dist:
      type: constant_string
      value: 'false'
  - name: instance
    type: String
    dist:
      type: replica_string
      replica_prefix: '10.0.162.'
      replica: 30
  - name: job_name
    type: String
    dist:
      type: constant_string
      value: 'kubelet'
  - name: metrics_path
    type: String
    dist:
      type: constant_string
      value: '/metrics'
  - name: namespace
    type: String
    dist:
      type: constant_string
      value: 'kube-system'
  - name: operation_type
    type: String
    dist:
      type: weighted_preset
      preset:
        - value: 'create_pod'
          weight: 1
        - value: 'sync'
          weight: 1
        - value: 'terminate'
          weight: 1
        - value: 'sync'
          weight: 1
fields:
  - name: greptime_value
    type: Float
    dist: 
      type: mono_inc
      step: 10
