start: "2024-02-08T00:00:00+08:00"
end: "2024-03-08T00:00:00+08:00"
interval: 30 # 30s
precision: 1000 # ms
tags:
  - name: endpoint
    type: String
    dist:
      type: constant_string
      value: 'https-metrics'
  - name: env
    type: STRING
    dist:
      type: constant_string
      value: 'prod'
  - name: holiday
    type: String
    dist:
      type: constant_boolean
      value: 'false'
  - name: instance
    type: String
    dist:
      type: replica_string
      replica_prefix: '10.0.162.'
      replica: 30
  - name: node
    type: String
    dist:
      type: replica_string
      replica_prefix: '10.0.162.'
      replica: 30
  - name: job_name
    type: String
    dist:
      type: constant_string
      value: 'kubelet'
  - name: metrics_path
    type: String
    dist:
      type: constant_string
      value: '/metrics'
  - name: namespace
    type: String
    dist:
      type: constant_string
      value: 'kube-system'
  - name: state
    type: String
    dist:
      type: weighted_preset
      preset:
        - value: 'actual_state_of_world'
          weight: 1
        - value: 'desired_state_of_world'
          weight: 1
  - name: plugin_name
    type: String
    dist:
      type: weighted_preset
      preset:
        - value: 'kubernetes.io/configmap'
          weight: 8
        - value: 'kubernetes.io/csi:ebs.csi.aws.com'
          weight: 10
        - value: 'kubernetes.io/csi:efs.csi.aws.com'
          weight: 2
        - value: 'kubernetes.io/empty-dir'
          weight: 8
        - value: 'kubernetes.io/host-path'
          weight: 8
        - value: 'kubernetes.io/projected'
          weight: 8
        - value: 'kubernetes.io/secret'
          weight: 8
fields:
  - name: greptime_value
    type: Float
    dist: 
      type: random_int
      lower_bound: 1
      upper_bound: 50
