end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: gcrm
      weight: 1
    - value: node-exporter
      weight: 1
    - value: loki
      weight: 1
    - value: cert-manager-webhook
      weight: 1
    - value: runner
      weight: 1
    - value: victoria-metrics-cluster-vmstorage
      weight: 1
    - value: cert-manager-controller
      weight: 1
    - value: config-reloader
      weight: 1
    - value: jarvis-producer
      weight: 1
    - value: kube-fledged
      weight: 1
    - value: debug
      weight: 1
    - value: alertmanager
      weight: 1
    - value: etcd
      weight: 1
    - value: datanode
      weight: 1
    - value: jarvis-consumer
      weight: 1
    - value: tempo
      weight: 1
    - value: kubernetes-replicator
      weight: 1
    - value: frontend
      weight: 1
    - value: vector
      weight: 1
    - value: tudigong
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    type: constant_string
    value: http
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    type: constant_string
    value: 10.0.169.98:8080
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: job
  type: String
- dist:
    preset:
    - value: gcrm
      weight: 1
    - value: monitoring
      weight: 1
    - value: loki
      weight: 1
    - value: cert-manager
      weight: 1
    - value: robusta
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: jarvis
      weight: 1
    - value: kube-fledged
      weight: 1
    - value: debug
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: greptimedb
      weight: 1
    - value: tempo
      weight: 1
    - value: kubernetes-replicator
      weight: 1
    - value: vector
      weight: 1
    - value: tudigong
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: argo-cd
      weight: 1
    - value: gcp
      weight: 1
    - value: greptimedb-standalone
      weight: 1
    - value: reloader
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: loki-write-1
      weight: 1
    - value: cert-manager-webhook-87b57d98b-48p4n
      weight: 1
    - value: robusta-runner-54f97bcbdf-kjvdv
      weight: 1
    - value: victoria-metrics-cluster-vmstorage-0
      weight: 1
    - value: cert-manager-6b6c8845d7-xvwcj
      weight: 1
    - value: prometheus-prometheus-kube-prometheus-prometheus-0
      weight: 1
    - value: jarvis-producer-59875c87-sqjbv
      weight: 1
    - value: kube-fledged-controller-584c9bbf47-bz95c
      weight: 1
    - value: debug-796b745495-bcz88
      weight: 1
    - value: alertmanager-prometheus-kube-prometheus-alertmanager-0
      weight: 1
    - value: prometheus-prometheus-node-exporter-8fcnl
      weight: 1
    - value: loki-backend-1
      weight: 1
    - value: etcd-0
      weight: 1
    - value: greptimedb-datanode-2
      weight: 1
    - value: greptimedb-datanode-0
      weight: 1
    - value: etcd-2
      weight: 1
    - value: jarvis-consumer-86999fbb4f-f6gdm
      weight: 1
    - value: tempo-0
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: cpu
  name: resource
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics
  name: service
  type: String
- dist:
    preset:
    - value: 3376581e-6254-4afd-8562-f1885788dba5
      weight: 1
    - value: b815caae-7d3e-4c67-905b-4b642927a3bf
      weight: 1
    - value: a06c9ae9-4444-4d61-853f-75c6f75e902f
      weight: 1
    - value: a9057afa-0e36-4dbc-b74a-32d465b9b935
      weight: 1
    - value: c46adf86-9c7b-49ac-889a-0375565e739c
      weight: 1
    - value: 164e4cc7-d5f8-44fd-9cb0-cdf2fd9d8124
      weight: 1
    - value: d8ed84cb-316d-4dc2-9fd5-4b58d0f46eb1
      weight: 1
    - value: 46e70299-f4da-4519-9d6c-97431b411fe9
      weight: 1
    - value: 85c9f743-c7d2-470b-817e-a96a1067da1c
      weight: 1
    - value: ee83cd5c-99b0-4252-9f02-80c0da28b1c9
      weight: 1
    - value: bf27637f-3b38-47fb-9479-900854ecdc3d
      weight: 1
    - value: 91abd95e-7869-4b34-8aed-f6542796221d
      weight: 1
    - value: b2555201-3292-4f74-af79-2f6f0cdfddb5
      weight: 1
    - value: e7b453fc-b57d-4923-9313-fa52109e1d1f
      weight: 1
    - value: 9438494a-a60d-455b-82d1-7efee586ca4f
      weight: 1
    - value: a65f62a4-a3c6-4932-8013-3de7e2a8c4e9
      weight: 1
    - value: faa375ea-9345-4b17-99f0-a3a2620359ea
      weight: 1
    - value: e6c90cb5-0d94-45ac-8906-96ea20b7e288
      weight: 1
    - value: d06328a4-e1ad-4e34-a1a4-3e899b395bf6
      weight: 1
    - value: d3ea6a07-4cf9-48a6-a773-116e0dfcecba
      weight: 1
    type: weighted_preset
  name: uid
  type: String
- dist:
    type: constant_string
    value: core
  name: unit
  type: String
