end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb815caae_7d3e_4c67_905b_4b642927a3bf.slice/cri-containerd-8d17e5edefa524816328b60edcb6e4aafb76faebdeab5cede3827a8b01f209e1.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6885b44c_57e5_4cda_b825_c866131ec44b.slice/cri-containerd-72b4db149d70dbc6c8d6331d191ad2d446a804f0fcac0670d54737d15040fabc.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6b5d3d76_f4aa_4532_8146_f274ffb204d9.slice/cri-containerd-72d1caa18908556873c55815e1de0e025e07f56cac249b89947e751b7697b796.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3f843444_5019_4c69_a65b_f594bbfac851.slice/cri-containerd-1a8bc08526d153ec51e68ac20d9adf168588b601ccc9ef8bf6bc23341c638ac4.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7b37f8fe_61f8_4db8_9353_7d64e743a6f2.slice/cri-containerd-6f241da94d4a7c0f9b4a3e0decbf1d998185ff5c057ccd15a722bfadcf5b889a.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb2555201_3292_4f74_af79_2f6f0cdfddb5.slice/cri-containerd-093300ab8b9a92cd0a24a818214457c028a54c1bc01a73981b6bf5f1c0a085cb.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podfab7316e_2b2a_4549_8fe6_ce23a673ffb8.slice/cri-containerd-22f3aa3488c83a96c1b24990d73e5eda8c343f2f0feb0a700acd79a61b586f1b.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod20b1545a_2bf7_4706_a110_54757204fd0c.slice/cri-containerd-88613e1155353c4d10ce1637d8e5c5a54783e27a3a68cbd11d6f27977f77ef83.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pode3274291_4a8a_4d57_a84b_fd6f6b8ac4c1.slice/cri-containerd-9fec6048b21a6904ae7af6782075d44a29b41ae007152be5b0171ee3e41d11fb.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbc17369e_e588_45af_b620_0f4506448599.slice/cri-containerd-f9a25fc8a5cc6da39d07947cd8788cf3b0b47349cee677ca08c6eb705a2af967.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod545e0c94_0848_4125_a3bd_3414093d43bb.slice/cri-containerd-a391c6a7ddf92ca5711446769f1cb83dc420dfe1fd44cc814cd337a983f75954.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3376581e_6254_4afd_8562_f1885788dba5.slice/cri-containerd-d2b4b1ba2e32caaa0731a970fb89a28c0bf07b73bfde388a34f0ae213891a4ac.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6260f409_9953_4ffb_8c7f_def56f2cd321.slice/cri-containerd-7c8f55739cac3157a3117e6c99f9abbae1eabb9eca2e88096831db1774292f2c.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod4b4376bf_278b_4ec6_966f_733a7fd34025.slice/cri-containerd-9650f00c07c4de841cced12e845278bf2251d6cda41ea1e8d5948ea862d3df0d.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbaf3287c_bb00_42c5_b78e_25c69c403ba4.slice/cri-containerd-591ea4f34b4f72bb9bb25d29c7866f860e8f5ad99376ac6f506bc25d9f71031e.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1e77dda5_1cd4_4a6b_a78b_14d38ecea5bd.slice/cri-containerd-6d92fbb5f5ac45b6ba52228df3c77f6d6beeba8ddd64e8e226f90ed1f1d55d97.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod418b0360_155e_4064_9bff_a98836a163b1.slice/cri-containerd-e034c3632927bf14925e619967977ba86b328b631a9f7d23228727925cee3fa5.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podf0d7d2b7_a00d_4d96_8f02_fd51bedc75e6.slice/cri-containerd-d4d7ef3758a8452657825733a94569d558f71a2e4b42dd87ee490227154e2649.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd947eed5_d0a1_48e4_b315_257ba5c5965d.slice/cri-containerd-fea921efb238df33972cef7a89474ff5bb12a610e7b56062433235b07d5dde80.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb178ecfc_7cce_4640_a0c8_000da84ae66d.slice/cri-containerd-8b3a83e0cce9ce0529611e42fc692ed57e2f7d12c31fba0e9b4786868e1362b8.scope
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    type: constant_string
    value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    preset:
    - value: eni77bff7ff384
      weight: 1
    - value: enidaec5e37acb
      weight: 1
    - value: eni81433a5855d
      weight: 1
    - value: eni65d63236344
      weight: 1
    - value: eth0
      weight: 1
    - value: eni413fc45e01c
      weight: 1
    - value: eni9583a808420
      weight: 1
    - value: eni9eeae9ce044
      weight: 1
    - value: enid83171f9d70
      weight: 1
    - value: enidf15009399d
      weight: 1
    - value: eth1
      weight: 1
    - value: eni390a5f44f34
      weight: 1
    - value: eni91c5eb97814
      weight: 1
    - value: eni4b06dd7a8b4
      weight: 1
    - value: eni641d489c074
      weight: 1
    - value: eth2
      weight: 1
    - value: eni789b0124656
      weight: 1
    - value: enib973d9d0097
      weight: 1
    - value: enib762e5779dc
      weight: 1
    - value: enifb09756d9b5
      weight: 1
    type: weighted_preset
  name: interface
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: 8d17e5edefa524816328b60edcb6e4aafb76faebdeab5cede3827a8b01f209e1
      weight: 1
    - value: 72b4db149d70dbc6c8d6331d191ad2d446a804f0fcac0670d54737d15040fabc
      weight: 1
    - value: 72d1caa18908556873c55815e1de0e025e07f56cac249b89947e751b7697b796
      weight: 1
    - value: 1a8bc08526d153ec51e68ac20d9adf168588b601ccc9ef8bf6bc23341c638ac4
      weight: 1
    - value: 6f241da94d4a7c0f9b4a3e0decbf1d998185ff5c057ccd15a722bfadcf5b889a
      weight: 1
    - value: 093300ab8b9a92cd0a24a818214457c028a54c1bc01a73981b6bf5f1c0a085cb
      weight: 1
    - value: 22f3aa3488c83a96c1b24990d73e5eda8c343f2f0feb0a700acd79a61b586f1b
      weight: 1
    - value: 88613e1155353c4d10ce1637d8e5c5a54783e27a3a68cbd11d6f27977f77ef83
      weight: 1
    - value: 9fec6048b21a6904ae7af6782075d44a29b41ae007152be5b0171ee3e41d11fb
      weight: 1
    - value: f9a25fc8a5cc6da39d07947cd8788cf3b0b47349cee677ca08c6eb705a2af967
      weight: 1
    - value: a391c6a7ddf92ca5711446769f1cb83dc420dfe1fd44cc814cd337a983f75954
      weight: 1
    - value: d2b4b1ba2e32caaa0731a970fb89a28c0bf07b73bfde388a34f0ae213891a4ac
      weight: 1
    - value: 7c8f55739cac3157a3117e6c99f9abbae1eabb9eca2e88096831db1774292f2c
      weight: 1
    - value: 9650f00c07c4de841cced12e845278bf2251d6cda41ea1e8d5948ea862d3df0d
      weight: 1
    - value: 591ea4f34b4f72bb9bb25d29c7866f860e8f5ad99376ac6f506bc25d9f71031e
      weight: 1
    - value: 6d92fbb5f5ac45b6ba52228df3c77f6d6beeba8ddd64e8e226f90ed1f1d55d97
      weight: 1
    - value: e034c3632927bf14925e619967977ba86b328b631a9f7d23228727925cee3fa5
      weight: 1
    - value: d4d7ef3758a8452657825733a94569d558f71a2e4b42dd87ee490227154e2649
      weight: 1
    - value: fea921efb238df33972cef7a89474ff5bb12a610e7b56062433235b07d5dde80
      weight: 1
    - value: 8b3a83e0cce9ce0529611e42fc692ed57e2f7d12c31fba0e9b4786868e1362b8
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: monitoring
      weight: 1
    - value: kube-system
      weight: 1
    - value: argo-cd
      weight: 1
    - value: gcrm
      weight: 1
    - value: etcd
      weight: 1
    - value: vector
      weight: 1
    - value: argo-workflows
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: external-dns
      weight: 1
    - value: robusta
      weight: 1
    - value: kube-fledged
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: cert-manager
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: greptimedb
      weight: 1
    - value: loki
      weight: 1
    - value: ingress-nginx
      weight: 1
    - value: tempo
      weight: 1
    - value: default
      weight: 1
    - value: kafka
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    - value: prometheus-prometheus-node-exporter-f9zfx
      weight: 1
    - value: kube-proxy-htsdp
      weight: 1
    - value: argo-cd-argocd-application-controller-0
      weight: 1
    - value: prometheus-prometheus-node-exporter-8fcnl
      weight: 1
    - value: efs-csi-node-l4rxj
      weight: 1
    - value: aws-node-cjttw
      weight: 1
    - value: efs-csi-node-t2vwk
      weight: 1
    - value: aws-node-8h9x6
      weight: 1
    - value: kube-proxy-5q9j4
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    - value: kube-proxy-vrnnh
      weight: 1
    - value: efs-csi-node-x2ht5
      weight: 1
    - value: aws-node-hbdbn
      weight: 1
    - value: etcd-1
      weight: 1
    - value: aws-node-mpvsz
      weight: 1
    - value: prometheus-prometheus-node-exporter-xwxj4
      weight: 1
    - value: vector-dbg5j
      weight: 1
    - value: ebs-csi-controller-7569cdd674-whx4z
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
