end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: container
  type: String
- dist:
    type: constant_string
    value: http
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    type: constant_string
    value: 10.0.169.98:8080
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: job
  type: String
- dist:
    preset:
    - value: dedicated-etcd
      weight: 1
    - value: robusta
      weight: 1
    - value: cert-manager
      weight: 1
    - value: vector
      weight: 1
    - value: kafka
      weight: 1
    - value: tudigong
      weight: 1
    - value: loki
      weight: 1
    - value: monitoring
      weight: 1
    - value: gcpa
      weight: 1
    - value: etcd
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: argo-cd
      weight: 1
    - value: kube-system
      weight: 1
    - value: bytebase
      weight: 1
    - value: reloader
      weight: 1
    - value: external-dns
      weight: 1
    - value: greptimedb
      weight: 1
    - value: gcp
      weight: 1
    - value: jarvis
      weight: 1
    - value: argo-workflows
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: 'true'
      weight: 1
    - value: null
      weight: 1
    type: weighted_preset
  name: owner_is_controller
  type: String
- dist:
    preset:
    - value: StatefulSet
      weight: 1
    - value: ReplicaSet
      weight: 1
    - value: DaemonSet
      weight: 1
    - value: Workflow
      weight: 1
    - value: null
      weight: 1
    type: weighted_preset
  name: owner_kind
  type: String
- dist:
    preset:
    - value: etcd
      weight: 1
    - value: robusta-forwarder-5fc46ff74
      weight: 1
    - value: cert-manager-cainjector-57c5ccd8b4
      weight: 1
    - value: vector
      weight: 1
    - value: kafka-controller
      weight: 1
    - value: tudigong-6d886f5b4f
      weight: 1
    - value: loki-write
      weight: 1
    - value: loki-backend
      weight: 1
    - value: prometheus-prometheus-node-exporter
      weight: 1
    - value: gcpa-mtls-6c446fbd88
      weight: 1
    - value: victoria-metrics-cluster-vminsert-79f4c65d45
      weight: 1
    - value: argo-cd-argocd-server-6c544f855d
      weight: 1
    - value: efs-csi-node
      weight: 1
    - value: bytebase
      weight: 1
    - value: prometheus-kube-state-metrics-8f664f9c8
      weight: 1
    - value: aws-node
      weight: 1
    - value: victoria-metrics-cluster-vmstorage
      weight: 1
    - value: reloader-reloader-589bd4796c
      weight: 1
    - value: efs-csi-controller-bc466c4b6
      weight: 1
    - value: etcd-backup-1741435200
      weight: 1
    type: weighted_preset
  name: owner_name
  type: String
- dist:
    preset:
    - value: etcd-2
      weight: 1
    - value: robusta-forwarder-5fc46ff74-2m2hf
      weight: 1
    - value: cert-manager-cainjector-57c5ccd8b4-mk6sm
      weight: 1
    - value: vector-n6r8q
      weight: 1
    - value: kafka-controller-0
      weight: 1
    - value: tudigong-6d886f5b4f-hrkt8
      weight: 1
    - value: loki-write-1
      weight: 1
    - value: vector-dbg5j
      weight: 1
    - value: loki-backend-1
      weight: 1
    - value: prometheus-prometheus-node-exporter-8fcnl
      weight: 1
    - value: loki-backend-0
      weight: 1
    - value: gcpa-mtls-6c446fbd88-xbkhr
      weight: 1
    - value: etcd-0
      weight: 1
    - value: victoria-metrics-cluster-vminsert-79f4c65d45-hb62s
      weight: 1
    - value: argo-cd-argocd-server-6c544f855d-4g99m
      weight: 1
    - value: efs-csi-node-l4rxj
      weight: 1
    - value: bytebase-0
      weight: 1
    - value: prometheus-kube-state-metrics-8f664f9c8-cdcrg
      weight: 1
    - value: aws-node-cjttw
      weight: 1
    - value: victoria-metrics-cluster-vmstorage-0
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics
  name: service
  type: String
- dist:
    preset:
    - value: e6c90cb5-0d94-45ac-8906-96ea20b7e288
      weight: 1
    - value: 8c7f1453-6807-45d3-864e-2f72a72bee98
      weight: 1
    - value: e06cc089-2774-4ef9-bf92-f423d97c2dbe
      weight: 1
    - value: d7fcc62c-c631-4ab8-94e6-f3c37e135170
      weight: 1
    - value: e5b24262-5e15-4ee2-b50d-6a23528a163d
      weight: 1
    - value: 2a796b6d-fc8d-4c1d-a606-c84a92e78c08
      weight: 1
    - value: a06c9ae9-4444-4d61-853f-75c6f75e902f
      weight: 1
    - value: d947eed5-d0a1-48e4-b315-257ba5c5965d
      weight: 1
    - value: e7b453fc-b57d-4923-9313-fa52109e1d1f
      weight: 1
    - value: b2555201-3292-4f74-af79-2f6f0cdfddb5
      weight: 1
    - value: 08b1ae46-f5a0-4aa0-8e72-9c712c33900b
      weight: 1
    - value: 944459b7-c814-41f1-996c-8d9f8c6630a6
      weight: 1
    - value: b2f9100d-ea63-4555-9955-b24df842b7b1
      weight: 1
    - value: 5732c87c-7eef-4360-8149-8f28461370f8
      weight: 1
    - value: f491c71f-1804-4ac0-a150-ccc7009e94ea
      weight: 1
    - value: fab7316e-2b2a-4549-8fe6-ce23a673ffb8
      weight: 1
    - value: 5c3dc06d-50f5-48e9-b7f2-f1492bb6a2ef
      weight: 1
    - value: 79dabf76-afa9-4b1a-98bb-a50d925472a1
      weight: 1
    - value: 20b1545a-2bf7-4706-a110-54757204fd0c
      weight: 1
    - value: 164e4cc7-d5f8-44fd-9cb0-cdf2fd9d8124
      weight: 1
    type: weighted_preset
  name: uid
  type: String
