end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: container
  type: String
- dist:
    type: constant_string
    value: http
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    type: constant_string
    value: 10.0.169.98:8080
  name: instance
  type: String
- dist:
    type: constant_string
    value: kube-state-metrics
  name: job
  type: String
- dist:
    preset:
    - value: monitoring
      weight: 1
    - value: gcp
      weight: 1
    - value: etcd
      weight: 1
    - value: greptimedb
      weight: 1
    - value: bytebase
      weight: 1
    - value: loki
      weight: 1
    - value: jarvis
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: greptimedb-standalone
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: tempo
      weight: 1
    - value: kafka
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
      weight: 1
    - value: redis-data-gcp-redis-master-0
      weight: 1
    - value: data-etcd-2
      weight: 1
    - value: datanode-greptimedb-datanode-2
      weight: 1
    - value: data-etcd-1
      weight: 1
    - value: bytebase-volume
      weight: 1
    - value: datanode-greptimedb-datanode-0
      weight: 1
    - value: data-loki-backend-0
      weight: 1
    - value: jarvis-efs-pvc
      weight: 1
    - value: data-internal-greptimedb-standalone-0
      weight: 1
    - value: data-greptimedb-standalone-0
      weight: 1
    - value: data-etcd-0
      weight: 1
    - value: alertmanager-prometheus-kube-prometheus-alertmanager-db-alertmanager-prometheus-kube-prometheus-alertmanager-0
      weight: 1
    - value: vmstorage-volume-victoria-metrics-cluster-vmstorage-1
      weight: 1
    - value: datanode-greptimedb-datanode-1
      weight: 1
    - value: data-loki-write-0
      weight: 1
    - value: vmstorage-volume-victoria-metrics-cluster-vmstorage-0
      weight: 1
    - value: data-loki-write-1
      weight: 1
    - value: data-loki-backend-1
      weight: 1
    - value: storage-tempo-0
      weight: 1
    type: weighted_preset
  name: persistentvolumeclaim
  type: String
- dist:
    preset:
    - value: Bound
      weight: 1
    - value: Pending
      weight: 1
    - value: Lost
      weight: 1
    type: weighted_preset
  name: phase
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics-8f664f9c8-cdcrg
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-state-metrics
  name: service
  type: String
