end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: cert-manager
      weight: 1
    - value: argo-cd
      weight: 1
    - value: reloader
      weight: 1
    - value: vector
      weight: 1
    - value: etcd
      weight: 1
    - value: kafka
      weight: 1
    - value: tudigong
      weight: 1
    - value: gcrm
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: karpenter
      weight: 1
    - value: kubernetes-event-exporter
      weight: 1
    - value: internal-ingress-nginx
      weight: 1
    - value: kube-system
      weight: 1
    - value: dedicated-etcd
      weight: 1
    - value: greptimedb-operator
      weight: 1
    - value: debug
      weight: 1
    - value: kubernetes-replicator
      weight: 1
    - value: default
      weight: 1
    - value: gcpa
      weight: 1
    - value: sealed-secrets
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
