end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    preset:
    - value: null
      weight: 1
    - value: csi-driver-registrar
      weight: 1
    - value: controller
      weight: 1
    - value: gcp
      weight: 1
    - value: jmx-exporter
      weight: 1
    - value: gcrm
      weight: 1
    - value: kube-prometheus-stack
      weight: 1
    - value: ebs-plugin
      weight: 1
    - value: external-dns
      weight: 1
    - value: gcpa-mtls
      weight: 1
    - value: vector
      weight: 1
    - value: csi-provisioner
      weight: 1
    - value: liveness-probe
      weight: 1
    - value: csi-snapshotter
      weight: 1
    - value: meta
      weight: 1
    - value: applicationset-controller
      weight: 1
    - value: manager
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: node-driver-registrar
      weight: 1
    - value: victoria-metrics-cluster-vminsert
      weight: 1
    type: weighted_preset
  name: container
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod5c3dc06d_50f5_48e9_b7f2_f1492bb6a2ef.slice/cri-containerd-bb008866560bf7df3800f212ef7a58a7e748e8e5278ffede72f610c5da252b28.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podb8d76005_eca1_46f2_b2ca_2d28ce191c40.slice/cri-containerd-54167cc6736eeb6895fd977b7b8b5cfba18a57231b81c6e894382102c0b9c5d6.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6bdfa225_b9c0_4ba9_9846_65789e0598f2.slice/cri-containerd-350e7b1303fb3d9e9faef658990d101349b823a6c81e011a64b4892ef33e4a40.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod438ceb9c_52bb_4988_bf02_f676fa4f25bc.slice/cri-containerd-235917935b4445f72612f412fc4af6d4bb13095e569af31a58ad81d566dd8b08.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6885b44c_57e5_4cda_b825_c866131ec44b.slice/cri-containerd-72b4db149d70dbc6c8d6331d191ad2d446a804f0fcac0670d54737d15040fabc.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod9bc9138e_ce8a_4dc6_a7d5_2d003a8278d8.slice/cri-containerd-68b47bd464e78eed2c12155ac76f0163ddfa7f7195040c34542444cb3d476031.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podfb58676a_eb70_41ea_aef0_fc091d30c889.slice/cri-containerd-3f05c4adf985bca067e325a08207205336712d6f1d905d54988582f3ad6fb678.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode5b24262_5e15_4ee2_b50d_6a23528a163d.slice/cri-containerd-c3110b384e00941010d8bd46f895f01fd9da1c33f649084ed68afa5b96f045c9.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda15a0269_ed01_45d4_8c7e_06333fdb9c88.slice/cri-containerd-91f7645e523496fdb85eaca12e9591b7a5c57cbcc1a6dad5c788bc7659ec1e2d.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3376581e_6254_4afd_8562_f1885788dba5.slice/cri-containerd-7a0882b6f6ed1849dc9cb5a28964d735b6571e48626bd13a4d559cc6d6c7c4d6.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3303d76c_68f3_43d1_825e_e9454fd6bf0d.slice/cri-containerd-b3d13c9d72c0a3332abcbe4ac1e9df4e14f3563be453394e32cfdd49255e38d3.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd5571f30_c2bf_4bda_8632_05d64baa22f9.slice/cri-containerd-b871741ed5ea0e1f46cb4284b4ae4e7ed075ef7c55bab71b61ec50303258b7dd.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podfb58676a_eb70_41ea_aef0_fc091d30c889.slice/cri-containerd-caef6f5282434ce00ce7d2bde7ed869f3bbd9cdd916743fde92616431e2aa6ea.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod944459b7_c814_41f1_996c_8d9f8c6630a6.slice/cri-containerd-e3431874ff735e76e7596638f91d9b7bcba929b9d82ffa53f3043cb0e3845ed0.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3589b6c1_9886_4b29_89ce_736888c6bbcd.slice/cri-containerd-b4022f119f874de41bfe389c5c7d6806950f17b62b0d4ae283bf1a2fbbb7c37c.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod48f5b4e8_7c2b_400a_bb2c_8ef809146e17.slice/cri-containerd-454f9ce52e791689b704fcda0b2c74c636d2d1a355ab8743382e2689622696de.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podb815caae_7d3e_4c67_905b_4b642927a3bf.slice/cri-containerd-8d17e5edefa524816328b60edcb6e4aafb76faebdeab5cede3827a8b01f209e1.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod78d43f95_93b7_4e5b_9d25_8cc0dcc8a56c.slice/cri-containerd-59e0ac6d05d16781e8528879233691c6a0f56212de951965c350b5192a592236.scope
      weight: 1
    - value: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podfab7316e_2b2a_4549_8fe6_ce23a673ffb8.slice/cri-containerd-2a69ea099d4df2aab636de826cfe24e011792c512a647f7ba1c895bbc46249fe.scope
      weight: 1
    - value: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pode7b453fc_b57d_4923_9313_fa52109e1d1f.slice/cri-containerd-9f9f3b52a365ddc5a603d54f7ece513b0d2e9df8f015bffa131e023a723d4f41.scope
      weight: 1
    type: weighted_preset
  name: id
  type: String
- dist:
    preset:
    - value: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause:3.5
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.10.0-eks-1-29-7
      weight: 1
    - value: registry.k8s.io/ingress-nginx/controller@sha256:9724476b928967173d501040631b23ba07f47073999e80e34b120e8db5f234d5
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/greptime-cloud-platform:d64b16d-jvm-qa-global-20250121090729129
      weight: 1
    - value: docker.io/bitnami/jmx-exporter:1.0.1-debian-12-r9
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/gcrm:1d343d8f-20250117103307
      weight: 1
    - value: quay.io/prometheus-operator/prometheus-operator:v0.69.1
      weight: 1
    - value: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.34.0
      weight: 1
    - value: registry.k8s.io/external-dns/external-dns:v0.14.0
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/greptime-cloud-platform-agent:20250120040443-a1da33c
      weight: 1
    - value: docker.io/timberio/vector:0.42.0-distroless-libc
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v4.0.0-eks-1-29-7
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.12.0-eks-1-29-7
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v8.0.1-eks-1-30-12
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptimeteam/greptimedb-cloud:d78af306
      weight: 1
    - value: quay.io/argoproj/argocd:v2.10.1
      weight: 1
    - value: 465927837118.dkr.ecr.us-east-1.amazonaws.com/greptime/greptimedb-operator-dev:dev-20241205-1733403622-e2845cc7
      weight: 1
    - value: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptime-ent-cloud-dev:standalone-0227-weny-4
      weight: 1
    - value: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.11.0-eks-1-30-10
      weight: 1
    - value: docker.io/victoriametrics/vminsert:v1.94.0-cluster
      weight: 1
    type: weighted_preset
  name: image
  type: String
- dist:
    preset:
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    type: constant_string
    value: /metrics/cadvisor
  name: metrics_path
  type: String
- dist:
    preset:
    - value: bb008866560bf7df3800f212ef7a58a7e748e8e5278ffede72f610c5da252b28
      weight: 1
    - value: 54167cc6736eeb6895fd977b7b8b5cfba18a57231b81c6e894382102c0b9c5d6
      weight: 1
    - value: 350e7b1303fb3d9e9faef658990d101349b823a6c81e011a64b4892ef33e4a40
      weight: 1
    - value: 235917935b4445f72612f412fc4af6d4bb13095e569af31a58ad81d566dd8b08
      weight: 1
    - value: 72b4db149d70dbc6c8d6331d191ad2d446a804f0fcac0670d54737d15040fabc
      weight: 1
    - value: 68b47bd464e78eed2c12155ac76f0163ddfa7f7195040c34542444cb3d476031
      weight: 1
    - value: 3f05c4adf985bca067e325a08207205336712d6f1d905d54988582f3ad6fb678
      weight: 1
    - value: c3110b384e00941010d8bd46f895f01fd9da1c33f649084ed68afa5b96f045c9
      weight: 1
    - value: 91f7645e523496fdb85eaca12e9591b7a5c57cbcc1a6dad5c788bc7659ec1e2d
      weight: 1
    - value: 7a0882b6f6ed1849dc9cb5a28964d735b6571e48626bd13a4d559cc6d6c7c4d6
      weight: 1
    - value: b3d13c9d72c0a3332abcbe4ac1e9df4e14f3563be453394e32cfdd49255e38d3
      weight: 1
    - value: b871741ed5ea0e1f46cb4284b4ae4e7ed075ef7c55bab71b61ec50303258b7dd
      weight: 1
    - value: caef6f5282434ce00ce7d2bde7ed869f3bbd9cdd916743fde92616431e2aa6ea
      weight: 1
    - value: e3431874ff735e76e7596638f91d9b7bcba929b9d82ffa53f3043cb0e3845ed0
      weight: 1
    - value: b4022f119f874de41bfe389c5c7d6806950f17b62b0d4ae283bf1a2fbbb7c37c
      weight: 1
    - value: 454f9ce52e791689b704fcda0b2c74c636d2d1a355ab8743382e2689622696de
      weight: 1
    - value: 8d17e5edefa524816328b60edcb6e4aafb76faebdeab5cede3827a8b01f209e1
      weight: 1
    - value: 59e0ac6d05d16781e8528879233691c6a0f56212de951965c350b5192a592236
      weight: 1
    - value: 2a69ea099d4df2aab636de826cfe24e011792c512a647f7ba1c895bbc46249fe
      weight: 1
    - value: 9f9f3b52a365ddc5a603d54f7ece513b0d2e9df8f015bffa131e023a723d4f41
      weight: 1
    type: weighted_preset
  name: name
  type: String
- dist:
    preset:
    - value: bytebase
      weight: 1
    - value: kube-system
      weight: 1
    - value: vector
      weight: 1
    - value: ingress-nginx
      weight: 1
    - value: monitoring
      weight: 1
    - value: gcp
      weight: 1
    - value: external-dns
      weight: 1
    - value: kafka
      weight: 1
    - value: gcrm
      weight: 1
    - value: gcpa
      weight: 1
    - value: greptimedb
      weight: 1
    - value: loki
      weight: 1
    - value: argo-cd
      weight: 1
    - value: greptimedb-operator
      weight: 1
    - value: internal-greptimedb-standalone
      weight: 1
    - value: victoria-metrics-cluster
      weight: 1
    - value: jarvis
      weight: 1
    - value: kubernetes-event-exporter
      weight: 1
    - value: reloader
      weight: 1
    - value: etcd
      weight: 1
    type: weighted_preset
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: bytebase-0
      weight: 1
    - value: efs-csi-node-7ln4t
      weight: 1
    - value: vector-2xvqg
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-frtzs
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    - value: gcp-6fbc9cf564-k5968
      weight: 1
    - value: external-dns-5c99648766-lcjg4
      weight: 1
    - value: kafka-controller-0
      weight: 1
    - value: ingress-nginx-controller-646d774bc8-7qvh7
      weight: 1
    - value: gcrm-c9598d7f-hrrv2
      weight: 1
    - value: prometheus-kube-prometheus-operator-7dc7f7857d-9gcjt
      weight: 1
    - value: ebs-csi-node-qkksr
      weight: 1
    - value: gcpa-mtls-6c446fbd88-xbkhr
      weight: 1
    - value: vector-qwpl5
      weight: 1
    - value: greptimedb-flownode-0
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: efs-csi-controller-bc466c4b6-2542z
      weight: 1
    - value: efs-csi-node-l4rxj
      weight: 1
    - value: loki-backend-1
      weight: 1
    - value: loki-backend-0
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
