end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: node-exporter
  name: container
  type: String
- dist:
    type: constant_string
    value: http-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    type: weighted_preset
  name: hostname
  type: String
- dist:
    preset:
    - value: 10.0.162.53:9100
      weight: 1
    - value: 10.0.166.131:9100
      weight: 1
    - value: 10.0.162.77:9100
      weight: 1
    - value: 10.0.169.179:9100
      weight: 1
    - value: 10.0.175.164:9100
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: t4g.large
  name: instance_type
  type: String
- dist:
    type: constant_string
    value: node-exporter
  name: job
  type: String
- dist:
    type: constant_string
    value: monitoring
  name: namespace
  type: String
- dist:
    preset:
    - value: prometheus-prometheus-node-exporter-8fcnl
      weight: 1
    - value: prometheus-prometheus-node-exporter-xwxj4
      weight: 1
    - value: prometheus-prometheus-node-exporter-f9zfx
      weight: 1
    - value: prometheus-prometheus-node-exporter-bzhjw
      weight: 1
    - value: prometheus-prometheus-node-exporter-bpscm
      weight: 1
    type: weighted_preset
  name: pod
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: us-east-1
  name: region
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-node-exporter
  name: service
  type: String
- dist:
    type: constant_string
    value: us-east-1a
  name: zone
  type: String
