end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    preset:
    - value: '7.62939453125'
      weight: 1
    - value: '1.220703125'
      weight: 1
    - value: '0.0125'
      weight: 1
    - value: '0.078125'
      weight: 1
    - value: +Inf
      weight: 1
    - value: '298.0232238769531'
      weight: 1
    - value: '0.03125'
      weight: 1
    - value: '3.0517578125'
      weight: 1
    - value: '0.48828125'
      weight: 1
    - value: '19.073486328125'
      weight: 1
    - value: '47.6837158203125'
      weight: 1
    - value: '119.20928955078125'
      weight: 1
    - value: '0.1953125'
      weight: 1
    - value: '745.0580596923828'
      weight: 1
    - value: '0.005'
      weight: 1
    type: weighted_preset
  name: le
  type: String
- dist:
    type: constant_string
    value: /metrics
  name: metrics_path
  type: String
- dist:
    type: constant_string
    value: kube-system
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: list_podsandbox
      weight: 1
    - value: stop_container
      weight: 1
    - value: container_status
      weight: 1
    - value: list_images
      weight: 1
    - value: exec_sync
      weight: 1
    - value: list_containers
      weight: 1
    - value: image_status
      weight: 1
    - value: create_container
      weight: 1
    - value: status
      weight: 1
    - value: run_podsandbox
      weight: 1
    - value: podsandbox_status
      weight: 1
    - value: pull_image
      weight: 1
    - value: remove_podsandbox
      weight: 1
    - value: version
      weight: 1
    - value: image_fs_info
      weight: 1
    - value: remove_container
      weight: 1
    - value: start_container
      weight: 1
    - value: stop_podsandbox
      weight: 1
    - value: exec
      weight: 1
    type: weighted_preset
  name: operation_type
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
