end: '2021-01-01T00:00:00Z'
fields:
- dist:
    lower_bound: 1
    step: 10
    type: mono_inc
    upper_bound: 1000
  name: greptime_value
  type: Float
interval: 30
precision: 1000
start: '2021-01-01T00:00:00Z'
tags:
- dist:
    type: constant_string
    value: eks-us-east-1-qa1
  name: cluster
  type: String
- dist:
    type: constant_string
    value: https-metrics
  name: endpoint
  type: String
- dist:
    type: constant_string
    value: qa
  name: env
  type: String
- dist:
    type: constant_string
    value: 'false'
  name: holiday
  type: String
- dist:
    preset:
    - value: 10.0.166.131:10250
      weight: 1
    - value: 10.0.175.164:10250
      weight: 1
    - value: 10.0.162.53:10250
      weight: 1
    - value: 10.0.169.179:10250
      weight: 1
    - value: 10.0.162.77:10250
      weight: 1
    type: weighted_preset
  name: instance
  type: String
- dist:
    type: constant_string
    value: kubelet
  name: job
  type: String
- dist:
    preset:
    - value: '10'
      weight: 1
    - value: '0.025'
      weight: 1
    - value: '1'
      weight: 1
    - value: '0.5'
      weight: 1
    - value: '0.01'
      weight: 1
    - value: '0.25'
      weight: 1
    - value: '0.1'
      weight: 1
    - value: +Inf
      weight: 1
    - value: '5'
      weight: 1
    - value: '0.005'
      weight: 1
    - value: '0.05'
      weight: 1
    - value: '2.5'
      weight: 1
    type: weighted_preset
  name: le
  type: String
- dist:
    type: constant_string
    value: /metrics
  name: metrics_path
  type: String
- dist:
    type: constant_string
    value: kube-system
  name: namespace
  type: String
- dist:
    preset:
    - value: ip-10-0-166-131.ec2.internal
      weight: 1
    - value: ip-10-0-175-164.ec2.internal
      weight: 1
    - value: ip-10-0-162-53.ec2.internal
      weight: 1
    - value: ip-10-0-169-179.ec2.internal
      weight: 1
    - value: ip-10-0-162-77.ec2.internal
      weight: 1
    type: weighted_preset
  name: node
  type: String
- dist:
    preset:
    - value: update
      weight: 1
    - value: create
      weight: 1
    - value: sync
      weight: 1
    - value: terminated
      weight: 1
    type: weighted_preset
  name: operation_type
  type: String
- dist:
    type: constant_string
    value: monitoring/prometheus-kube-prometheus-prometheus
  name: prometheus
  type: String
- dist:
    type: constant_string
    value: prometheus-prometheus-kube-prometheus-prometheus-0
  name: prometheus_replica
  type: String
- dist:
    type: constant_string
    value: prometheus-kube-prometheus-kubelet
  name: service
  type: String
